import { Language, MenuItem, FAQItem, TranslationKey, Review } from './types';

export const TRANSLATIONS: Record<Language, Record<TranslationKey, string>> = {
  [Language.HE]: {
    nav_home: 'בית',
    nav_menu: 'תפריט',
    nav_gallery: 'גלריה',
    nav_about: 'אודות',
    nav_reviews: 'ביקורות',
    nav_faq: 'שאלות',
    nav_contact: 'צור קשר',
    hero_title: 'סובלאקי יווני כפר יאסיף',
    hero_subtitle: 'מסעדה יוונית אותנטית באווירה משפחתית',
    hero_cta_order: 'הזמן עכשיו',
    hero_cta_menu: 'לצפייה בתפריט',
    about_title: 'הסיפור שלנו',
    about_content_1:
      'אנחנו מביאים את הטעמים האותנטיים של יוון היישר לכפר יאסיף. מתכונים שעברו מדור לדור עם חומרי גלם טריים ואיכותיים.',
    about_content_2:
      'האווירה במסעדה משלבת אירוח חם עם מוזיקה יוונית שמחה, היוצרת חוויה קולינרית בלתי נשכחת.',
    gallery_title: 'גלריה',
    menu_title: 'התפריט שלנו',
    reviews_title: 'לקוחות מספרים',
    reviews_subtitle: 'תודה ללקוחות המדהימים שלנו על המילים החמות',
    faq_title: 'שאלות נפוצות',
    contact_title: 'יצירת קשר',
    footer_copyright: '© 2026 סובלאקי יווני כפר יאסיף. כל הזכויות שמורות.',
    footer_terms: 'תנאי שימוש',
    footer_privacy: 'מדיניות פרטיות',
    footer_accessibility: 'הצהרת נגישות',
    footer_follow_us: 'עקבו אחרינו',
    category_pita: 'בפיתה',
    category_plate: 'בצלחת',
    category_sides: 'תוספות',
    open_status_open: 'פתוח עכשיו',
    open_status_closed: 'סגור כעת',
    cookie_text:
      'אתר זה משתמש בעוגיות (Cookies) על מנת לשפר את חווית הגלישה ולהתאים את התוכן עבורך, בהתאם להוראות החוק.',
    cookie_accept: 'אני מסכים/ה',
    cookie_decline: 'לא תודה',
    form_title: 'השאר ביקורת',
    form_name: 'שם מלא',
    form_rating: 'דירוג כללי',
    form_time_rating: 'דרג את הזמן שבילית',
    form_comment: 'ספר לנו על החוויה שלך',
    form_submit: 'שלח ביקורת',
    form_success: 'תודה על המשוב שלך!',
  },
  [Language.EN]: {
    nav_home: 'Home',
    nav_menu: 'Menu',
    nav_gallery: 'Gallery',
    nav_about: 'About',
    nav_reviews: 'Reviews',
    nav_faq: 'FAQ',
    nav_contact: 'Contact',
    hero_title: 'Greek Souvlaki Kafr Yasif',
    hero_subtitle: 'Authentic Greek Restaurant with Family Atmosphere',
    hero_cta_order: 'Order Now',
    hero_cta_menu: 'View Menu',
    about_title: 'Our Story',
    about_content_1:
      'We bring the authentic flavors of Greece straight to Kafr Yasif. Recipes passed down through generations with fresh, high-quality ingredients.',
    about_content_2:
      'The restaurant atmosphere combines warm hospitality with joyful Greek music, creating an unforgettable culinary experience.',
    gallery_title: 'Gallery',
    menu_title: 'Our Menu',
    reviews_title: 'What Customers Say',
    reviews_subtitle: 'Thanks to our amazing customers for the kind words',
    faq_title: 'FAQ',
    contact_title: 'Contact Us',
    footer_copyright: '© 2026 Greek Souvlaki Kafr Yasif. All rights reserved.',
    footer_terms: 'Terms of Use',
    footer_privacy: 'Privacy Policy',
    footer_accessibility: 'Accessibility Statement',
    footer_follow_us: 'Follow Us',
    category_pita: 'Pita',
    category_plate: 'Plate',
    category_sides: 'Sides',
    open_status_open: 'Open Now',
    open_status_closed: 'Closed Now',
    cookie_text:
      'This website uses cookies to improve the browsing experience and customize content for you, in accordance with the law.',
    cookie_accept: 'I Accept',
    cookie_decline: 'Decline',
    form_title: 'Leave a Review',
    form_name: 'Full Name',
    form_rating: 'Overall Rating',
    form_time_rating: 'Rate Time Spent',
    form_comment: 'Tell us about your experience',
    form_submit: 'Submit Review',
    form_success: 'Thank you for your feedback!',
  },
  [Language.AR]: {
    nav_home: 'الرئيسية',
    nav_menu: 'القائمة',
    nav_gallery: 'المعرض',
    nav_about: 'من نحن',
    nav_reviews: 'التقييمات',
    nav_faq: 'أسئلة شائعة',
    nav_contact: 'اتصل بنا',
    hero_title: 'سوفلاكي يوناني كفر ياسيف',
    hero_subtitle: 'مطعم يوناني أصيل بجو عائلي',
    hero_cta_order: 'اطلب الآن',
    hero_cta_menu: 'شاهد القائمة',
    about_title: 'قصتنا',
    about_content_1:
      'نحضر النكهات اليونانية الأصيلة مباشرة إلى كفر ياسيف. وصفات متوارثة عبر الأجيال بمكونات طازجة وعالية الجودة.',
    about_content_2:
      'يجمع جو المطعم بين الضيافة الدافئة والموسيقى اليونانية المبهجة، مما يخلق تجربة طهي لا تُنسى.',
    gallery_title: 'معرض الصور',
    menu_title: 'قائمتنا',
    reviews_title: 'ماذا يقول عملاؤنا',
    reviews_subtitle: 'شكرًا لعملائنا الرائعين على كلماتهم الطيبة',
    faq_title: 'أسئلة شائعة',
    contact_title: 'اتصل بنا',
    footer_copyright: '© 2026 سوفلاكي يوناني كفر ياسيف. جميع الحقوق محفوظة.',
    footer_terms: 'شروط الاستخدام',
    footer_privacy: 'سياسة الخصوصية',
    footer_accessibility: 'بيان إمكانية الوصول',
    footer_follow_us: 'تابعنا',
    category_pita: 'في خبز بيتا',
    category_plate: 'في طبق',
    category_sides: 'إضافات',
    open_status_open: 'مفتوح الآن',
    open_status_closed: 'مغلق الآن',
    cookie_text:
      'يستخدم هذا الموقع ملفات تعريف الارتباط (Cookies) لتحسين تجربة التصفح وتخصيص المحتوى لك، وفقًا للقانون.',
    cookie_accept: 'أوافق',
    cookie_decline: 'لا شكرًا',
    form_title: 'أترك تقييماً',
    form_name: 'الاسم الكامل',
    form_rating: 'التقييم العام',
    form_time_rating: 'قيم الوقت الذي قضيته',
    form_comment: 'أخبرنا عن تجربتك',
    form_submit: 'إرسال التقييم',
    form_success: 'شكرا لملاحظاتك!',
  },
  [Language.RU]: {
    nav_home: 'Главная',
    nav_menu: 'Меню',
    nav_gallery: 'Галерея',
    nav_about: 'О нас',
    nav_reviews: 'Отзывы',
    nav_faq: 'ЧаВо',
    nav_contact: 'Контакты',
    hero_title: 'Греческий Сувлаки Кафр-Ясиф',
    hero_subtitle: 'Аутентичный греческий ресторан с семейной атмосферой',
    hero_cta_order: 'Заказать',
    hero_cta_menu: 'Меню',
    about_title: 'Наша история',
    about_content_1:
      'Мы привозим аутентичные вкусы Греции прямо в Кафр-Ясиф. Рецепты, передаваемые из поколения в поколение, и свежие ингредиенты.',
    about_content_2:
      'Атмосфера ресторана сочетает в себе теплое гостеприимство и веселую греческую музыку.',
    gallery_title: 'Галерея',
    menu_title: 'Наше Меню',
    reviews_title: 'Отзывы Клиентов',
    reviews_subtitle: 'Спасибо всем нашим замечательным клиентам за теплые слова',
    faq_title: 'Частые вопросы',
    contact_title: 'Связаться с нами',
    footer_copyright: '© 2026 Greek Souvlaki Kafr Yasif. Все права защищены.',
    footer_terms: 'Условия',
    footer_privacy: 'Конфиденциальность',
    footer_accessibility: 'Доступность',
    footer_follow_us: 'Подписывайтесь',
    category_pita: 'В пите',
    category_plate: 'На тарелке',
    category_sides: 'Гарниры',
    open_status_open: 'Открыто',
    open_status_closed: 'Закрыто',
    cookie_text:
      'Этот сайт использует файлы cookie для улучшения просмотра и персонализации контента в соответствии с законом.',
    cookie_accept: 'Принять',
    cookie_decline: 'Отклонить',
    form_title: 'Оставить отзыв',
    form_name: 'Полное имя',
    form_rating: 'Общая оценка',
    form_time_rating: 'Оцените проведенное время',
    form_comment: 'Расскажите о вашем опыте',
    form_submit: 'Отправить отзыв',
    form_success: 'Спасибо за ваш отзыв!',
  },
  [Language.EL]: {
    nav_home: 'Αρχική',
    nav_menu: 'Μενού',
    nav_gallery: 'Συλλογή',
    nav_about: 'Σχετικά',
    nav_reviews: 'Κριτικές',
    nav_faq: 'Συχνές Ερωτήσεις',
    nav_contact: 'Επικοινωνία',
    hero_title: 'Ελληνικό Σουβλάκι Καφρ Γιασίφ',
    hero_subtitle: 'Αυθεντικό Ελληνικό Εστιατόριο',
    hero_cta_order: 'Παραγγελία',
    hero_cta_menu: 'Δείτε το μενού',
    about_title: 'Η ιστορία μας',
    about_content_1: 'Φέρνουμε τις αυθεντικές γεύσεις της Ελλάδας απευθείας στο Kafr Yasif.',
    about_content_2:
      'Η ατμόσφαιρα του εστιατορίου συνδυάζει ζεστή φιλοξενία με χαρούμενη ελληνική μουσική.',
    gallery_title: 'Συλλογή',
    menu_title: 'Το Μενού μας',
    reviews_title: 'Τι λένε οι πελάτες',
    reviews_subtitle: 'Ευχαριστούμε τους υπέροχους πελάτες μας',
    faq_title: 'Συχνές Ερωτήσεις',
    contact_title: 'Επικοινωνία',
    footer_copyright: '© 2026 Greek Souvlaki Kafr Yasif.',
    footer_terms: 'Όροι',
    footer_privacy: 'Απόρρητο',
    footer_accessibility: 'Προσβασιμότητα',
    footer_follow_us: 'Ακολουθήστε μας',
    category_pita: 'Πίτα',
    category_plate: 'Μερίδα',
    category_sides: 'Συνοδευτικά',
    open_status_open: 'Ανοιχτά',
    open_status_closed: 'Κλειστό',
    cookie_text: 'Αυτός ο ιστότοπος χρησιμοποιεί cookies για τη βελτίωση της εμπειρίας περιήγησης.',
    cookie_accept: 'Αποδοχή',
    cookie_decline: 'Απόρριψη',
    form_title: 'Αφήστε μια κριτική',
    form_name: 'Ονοματεπώνυμο',
    form_rating: 'Γενική βαθμολογία',
    form_time_rating: 'Αξιολογήστε τον χρόνο',
    form_comment: 'Πείτε μας για την εμπειρία σας',
    form_submit: 'Υποβολή',
    form_success: 'Ευχαριστούμε για τα σχόλιά σας!',
  },
};

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    category: 'category_pita',
    price: 45,
    image: 'https://picsum.photos/400/300?random=1',
    name: {
      he: 'סובלאקי עוף',
      en: 'Chicken Souvlaki',
      ar: 'سوفلاكي دجاج',
      ru: 'Куриный Сувлаки',
      el: 'Σουβλάκι Κοτόπουλο',
    },
    description: {
      he: 'שיפודי עוף במרינדה יוונית, מוגש עם צזיקי, עגבניה, בצל וצ׳יפס בתוך פיתה יוונית',
      en: 'Chicken skewers in Greek marinade, served with tzatziki, tomato, onion and fries in pita',
      ar: 'أسياخ دجاج بتتبيلة يونانية، تقدم مع تزاتزيكي، طماطم، بصل وبطاطس في خبز بيتا',
      ru: 'Куриные шашлычки в греческом маринаде, подаются с дзадзики, овощами и фри',
      el: 'Σουβλάκι κοτόπουλο με τζατζίκι, ντομάτα, κρεμμύδι και πατάτες',
    },
  },
  {
    id: '2',
    category: 'category_pita',
    price: 48,
    image: 'https://picsum.photos/400/300?random=2',
    name: {
      he: 'גירוס עגל',
      en: 'Veal Gyros',
      ar: 'جيروس عجل',
      ru: 'Гирос из телятины',
      el: 'Γύρος Μοσχάρι',
    },
    description: {
      he: 'נתחי עגל דקים ועסיסיים, מוגש עם צזיקי, עגבניה, בצל וצ׳יפס',
      en: 'Thin juicy veal slices, served with tzatziki, tomato, onion and fries',
      ar: 'قطع عجل رفيعة وعصيرية، تقدم مع تزاتزيكي، طماطم، بصل وبطاطس',
      ru: 'Сочные кусочки телятины, подаются с дзадзики и овощами',
      el: 'Λεπτές φέτες μοσχαριού με τζατζίκι',
    },
  },
  {
    id: '3',
    category: 'category_plate',
    price: 85,
    image: 'https://picsum.photos/400/300?random=3',
    name: {
      he: 'צלחת מיקס',
      en: 'Mix Plate',
      ar: 'طبق مشكل',
      ru: 'Микс тарелка',
      el: 'Πιάτο Μιξ',
    },
    description: {
      he: 'שילוב של סובלאקי וגירוס, מוגש עם תוספות, סלט יווני ופיתה בצד',
      en: 'Combination of souvlaki and gyros, served with sides, Greek salad and pita',
      ar: 'مزيج من السوفلاكي والجيروس، يقدم مع إضافات، سلطة يونانية وخبز بيتا',
      ru: 'Сочетание сувлаки и гироса, подается с гарниром и салатом',
      el: 'Συνδυασμός σουβλάκι και γύρο',
    },
  },
  {
    id: '4',
    category: 'category_sides',
    price: 25,
    image: 'https://picsum.photos/400/300?random=4',
    name: {
      he: 'צ׳יפס יווני',
      en: 'Greek Fries',
      ar: 'بطاطس يونانية',
      ru: 'Греческий фри',
      el: 'Πατάτες',
    },
    description: {
      he: 'צ׳יפס עם גבינת פטה ואורגנו',
      en: 'Fries with feta cheese and oregano',
      ar: 'بطاطس مع جبنة فيتا وأوريغانو',
      ru: 'Фри с сыром фета и орегано',
      el: 'Πατάτες με φέτα και ρίγανη',
    },
  },
  {
    id: '5',
    category: 'category_pita',
    price: 52,
    image: 'https://picsum.photos/400/300?random=5',
    name: {
      he: 'קבב כבש',
      en: 'Lamb Kebab',
      ar: 'كباب خروف',
      ru: 'Кебаб из ягненка',
      el: 'Κεμπάπ Αρνί',
    },
    description: {
      he: 'קציצות בשר כבש עסיסיות על הגריל, עם טחינה, עמבה וירקות צלויים',
      en: 'Juicy grilled lamb patties with tahini, amba, and roasted vegetables',
      ar: 'فطائر لحم خروف عصيرية مشوية، مع طحينة، عمبة وخضروات مشوية',
      ru: 'Сочные котлеты из ягненка на гриле с тахини и овощами',
      el: 'Ζουμερά μπιφτέκια αρνιού στη σχάρα με ταχίνι',
    },
  },
  {
    id: '6',
    category: 'category_plate',
    price: 78,
    image: 'https://picsum.photos/400/300?random=6',
    name: {
      he: 'מוסקה',
      en: 'Moussaka',
      ar: 'مسقعة',
      ru: 'Мусака',
      el: 'Μουσακάς',
    },
    description: {
      he: 'מאפה שכבות חצילים, בשר בקר ברוטב עגבניות ורוטב בשמל עשיר',
      en: 'Baked layers of eggplant, ground beef in tomato sauce, and rich bechamel',
      ar: 'طبقات مخبوزة من الباذنجان، لحم بقر مفروم في صلصة الطماطم، وبشاميل غني',
      ru: 'Запеченные слои баклажанов, говяжьего фарша и соуса бешамель',
      el: 'Ψητές στρώσεις μελιτζάνας, κιμά και μπεσαμέλ',
    },
  },
  {
    id: '7',
    category: 'category_sides',
    price: 42,
    image: 'https://picsum.photos/400/300?random=7',
    name: {
      he: 'סלט יווני',
      en: 'Greek Salad',
      ar: 'سلطة يونانية',
      ru: 'Греческий салат',
      el: 'Χωριάτικη Σαλάτα',
    },
    description: {
      he: 'ירקות טריים, זיתי קלמטה וגבינת פטה אמיתית עם שמן זית ואורגנו',
      en: 'Fresh vegetables, Kalamata olives, and real Feta cheese with olive oil and oregano',
      ar: 'خضروات طازجة، زيتون كالاماتا وجبنة فيتا حقيقية مع زيت الزيتون والأوريغانو',
      ru: 'Свежие овощи, оливки Каламата и настоящий сыр Фета',
      el: 'Φρέσκα λαχανικά, ελιές Καλαμών και φέτα',
    },
  },
  {
    id: '8',
    category: 'category_sides',
    price: 38,
    image: 'https://picsum.photos/400/300?random=8',
    name: {
      he: 'חלומי מטוגן',
      en: 'Fried Halloumi',
      ar: 'حلوم مقلي',
      ru: 'Жареный Халуми',
      el: 'Χαλούμι',
    },
    description: {
      he: 'אצבעות גבינת חלומי פריכות, מוגש עם מטבל צזיקי',
      en: 'Crispy Halloumi cheese sticks, served with Tzatziki dip',
      ar: 'أصابع جبنة حلوم مقرمشة، تقدم مع صلصة التزاتزيكي',
      ru: 'Хрустящие палочки сыра Халуми, подаются с соусом Дзадзики',
      el: 'Τραγανά μπαστούνια χαλούμι με τζατζίκι',
    },
  },
];

// SEO Metadata for multi-language optimization
export const SEO_METADATA: Record<
  Language,
  {
    title: string;
    description: string;
    keywords: string;
    ogTitle: string;
    ogDescription: string;
    ogLocale: string;
  }
> = {
  [Language.HE]: {
    title: 'סובלקי יווני כפר יאסיף | Greek Souvlaki Kfar Yasif - מסעדה יוונית אותנטית',
    description:
      'סובלקי יווני אותנטי בכפר יאסיף. פיתה טרה, גירוס, שישודים ועוד. הזמן עכשיו! פתוח רביעי-שבת 13:00-01:00. התקשרו 04-812-2980. מסעדה יוונית מקומית',
    keywords:
      'סובלקי, גירוס, מסעדה יוונית, אוכל יווני, פיתה יוונית, שווארמה יוונית, כפר יאסיף, מסעדה בגליל, אוכל בצפון, סובלקי בפיתה, גירוס בפיטה',
    ogTitle: 'סובלקי יווני כפר יאסיף | מסעדה יוונית אותנטית',
    ogDescription:
      'הכי טוב סובלקי יווני בכפר יאסיף! פיתה טרה, גירוס עסיסי, שישודים על האש. פתוח רביעי-שבת 13:00-01:00. הזמן עכשיו!',
    ogLocale: 'he_IL',
  },
  [Language.AR]: {
    title: 'سوفلاكي يوناني كفر ياسيف | Greek Souvlaki Kafr Yasif - مطعم يوناني أصيل',
    description:
      'سوفلاكي يوناني أصيل في كفر ياسيف. خبز بيتا طازج، جيروس، أسياخ والمزيد. اطلب الآن! مفتوح الأربعاء-السبت 13:00-01:00. اتصل 04-812-2980. مطعم يوناني محلي',
    keywords:
      'سوفلاكي, جيروس, مطعم يوناني, طعام يوناني, خبز بيتا يوناني, شاورما يونانية, كفر ياسيف, مطعم في الجليل, طعام في الشمال, سوفلاكي في بيتا, جيروس في بيتا',
    ogTitle: 'سوفلاكي يوناني كفر ياسيف | مطعم يوناني أصيل',
    ogDescription:
      'أفضل سوفلاكي يوناني في كفر ياسيف! خبز بيتا طازج، جيروس طري، أسياخ مشوية. مفتوح الأربعاء-السبت 13:00-01:00. اطلب الآن!',
    ogLocale: 'ar_IL',
  },
  [Language.RU]: {
    title: 'Греческий сувлаки Кафр Ясиф | Greek Souvlaki Kfar Yasif - Греческий ресторан',
    description:
      'Аутентичный греческий сувлаки в Кафр Ясиф. Свежая пита, гирос, шашлыки и многое другое. Закажите сейчас! Открыто ср-сб 13:00-01:00. Тел 04-812-2980. Греческий ресторан',
    keywords:
      'сувлаки, гирос, греческий ресторан, греческая кухня, греческая пита, греческая шаурма, Кафр Ясиф, ресторан в Галилее, еда на севере, сувлаки в пите, гирос в пите',
    ogTitle: 'Греческий сувлаки Кафр Ясиф | Аутентичный греческий ресторан',
    ogDescription:
      'Лучший греческий сувлаки в Кафр Ясиф! Свежая пита, сочный гирос, шашлыки на углях. Открыто ср-сб 13:00-01:00. Закажите сейчас!',
    ogLocale: 'ru_IL',
  },
  [Language.EL]: {
    title: 'Ελληνικό σουβλάκι Κουφ Γιασίφ | Greek Souvlaki Kfar Yasif - Ελληνικό εστιατόριο',
    description:
      'Αυθεντικό ελληνικό σουβλάκι στο Κουφ Γιασίφ. Φρέσκος πίτες, γύρος, σουβλάκια και πολλά περισσότερα. Παραγγείλετε τώρα! Ανοιχτά Τετ-Σαβ 13:00-01:00. Τηλ 04-812-2980. Ελληνικό εστιατόριο',
    keywords:
      'σουβλάκι, γύρος, ελληνικό εστιατόριο, ελληνική κουζίνα, ελληνική πίτα, ελληνική σούβλα, Κουφ Γιασίφ, εστιατόριο στη Γαλιλαία, φαγητό στον βορρά, σουβλάκι στην πίτα, γύρος στην πίτα',
    ogTitle: 'Ελληνικό σουβλάκι Κουφ Γιασίφ | Αυθεντικό ελληνικό εστιατόριο',
    ogDescription:
      'Το καλύτερο ελληνικό σουβλάκι στο Κουφ Γιασίφ! Φρέσκος πίτες, ζουμερός γύρος, σουβλάκια στην φωτιά. Ανοιχτά Τετ-Σαβ 13:00-01:00. Παραγγείλετε τώρα!',
    ogLocale: 'el_IL',
  },
  [Language.EN]: {
    title: 'Greek Souvlaki Kafr Yasif | סובלקי יווני כפר יאסיף - Authentic Greek Restaurant',
    description:
      'Authentic Greek souvlaki in Kafr Yasif. Fresh pita, gyros, skewers & more. Order now! Open Wed-Sat 13:00-01:00. Call 04-812-2980. Local Greek restaurant',
    keywords:
      'souvlaki, gyros, greek restaurant, greek food, greek pita, greek shawarma, kafr yasif, galilee restaurant, northern israel food, souvlaki in pita, gyros in pita',
    ogTitle: 'Greek Souvlaki Kafr Yasif | Authentic Greek Restaurant',
    ogDescription:
      'Best Greek souvlaki in Kafr Yasif! Fresh pita, juicy gyros, grilled skewers. Open Wed-Sat 13:00-01:00. Order now!',
    ogLocale: 'en_IL',
  },
};

export const REVIEWS: Review[] = [
  // No fake reviews - waiting for real customer reviews!
];

export const FAQS: FAQItem[] = [
  {
    id: '1',
    question: {
      he: 'מה שעות הפעילות של המסעדה?',
      en: "What are the restaurant's opening hours?",
      ar: 'ما هي ساعات عمل المطعم؟',
      ru: 'Каковы часы работы ресторана?',
      el: 'Ποιες είναι οι ώρες λειτουργίας του εστιατορίου;',
    },
    answer: {
      he: 'המסעדה פתוחה בימים רביעי עד שבת, בין השעות 13:00 עד 01:00. ימים ראשון עד שלישי המסעדה סגורה.',
      en: 'The restaurant is open Wednesday to Saturday, between 13:00 and 01:00. Sunday to Tuesday the restaurant is closed.',
      ar: 'المطعم مفتوح من الأربعاء إلى السبت، بين الساعات 13:00 و 01:00. الأحد إلى الثلاثاء المطعم مغلق.',
      ru: 'Ресторан открыт со среды по субботу, с 13:00 до 01:00. Воскресенье-вторник ресторан закрыт.',
      el: 'Το εστιατόριο είναι ανοιχτό Τετάρτη έως Σάββατο, από 13:00 έως 01:00.',
    },
  },
  {
    id: '2',
    question: {
      he: 'איפה נמצאת המסעדה?',
      en: 'Where is the restaurant located?',
      ar: 'أين يقع المطعم؟',
      ru: 'Где находится ресторан?',
      el: 'Πού βρίσκεται το εστιατόριο;',
    },
    answer: {
      he: 'המסעדה ממוקמת בכביש 70, כפר יאסיף בגליל המערבי. ניתן להגיע בקלות עם Waze או Google Maps.',
      en: 'The restaurant is located on Route 70, Kafr Yasif in the Western Galilee. Easy to reach with Waze or Google Maps.',
      ar: 'يقع المطعم على طريق 70، كفر ياسيف في الجليل الغربي. يمكن الوصول بسهولة عبر Waze أو Google Maps.',
      ru: 'Ресторан находится на шоссе 70, Кафр-Ясиф в Западной Галилее. Легко добраться с Waze или Google Картами.',
      el: 'Το εστιατόριο βρίσκεται στην Επαρχιακή Οδό 70, Καφρ Γιασίφ στη Δυτική Γαλιλαία.',
    },
  },
  {
    id: '3',
    question: {
      he: 'מה המחיר של סובלאקי בפיתה?',
      en: 'What is the price of a pita souvlaki?',
      ar: 'ما هو سعر سوفلاكي في خبز بيتا؟',
      ru: 'Какова цена сувлаки в пите?',
      el: 'Πόσο κοστίζει το σουβλάκι στην πίτα;',
    },
    answer: {
      he: "סובלאקי בפיתה מתחיל מ-30₪ וכולל פיתה יוונית, שיפוד לבחירה, רוטב צזיקי/חריף, ירקות טריים וצ'יפס.",
      en: 'Pita souvlaki starts from ₪30 and includes Greek pita, skewer of choice, tzatziki/spicy sauce, fresh vegetables and fries.',
      ar: 'سوفلاكي في خبز بيتا يبدأ من 30 شيكل ويشمل خبز بيتا يوناني، سيخ حسب الاختيار، صلصة تزاتزيكي/حارة، خضروات طازجة وبطاطس.',
      ru: 'Сувлаки в пите стоит от 30 ₪ и включает греческую питу, шашлычок на выбор, соус цацики/острый, свежие овощи и картофель фри.',
      el: 'Το σουβλάκι στην πίτα ξεκινά από 30₪ και περιλαμβάνει ελληνική πίτα, σουβλάκι επιλογής, τζατζίκι/καυτερό, φρέσκα λαχανικά και πατάτες.',
    },
  },
  {
    id: '4',
    question: {
      he: 'האם יש אפשרויות טבעוניות או ללא גלוטן?',
      en: 'Are there vegan or gluten-free options?',
      ar: 'هل هناك خيارات نباتية أو خالية من الغلوتين؟',
      ru: 'Есть ли веганские или безглютеновые опции?',
      el: 'Υπάρχουν βεγαν ή χωρίς γλουτένη επιλογές;',
    },
    answer: {
      he: 'כן! יש לנו סובלאקי טבעוני בפיתה (30₪) וגם אפשרות לפיתה ללא גלוטן (40₪) עם כל סוגי השיפודים.',
      en: 'Yes! We have vegan souvlaki in pita (₪30) and also gluten-free pita option (₪40) with all types of skewers.',
      ar: 'نعم! لدينا سوفلاكي نباتي في خبز بيتا (30 شيكل) وخيار خبز بيتا خالي من الغلوتين (40 شيكل) مع جميع أنواع الأسياخ.',
      ru: 'Да! У нас есть веганский сувлаки в пите (30 ₪) и также безглютеновая пита (40 ₪) со всеми видами шашлычков.',
      el: 'Ναι! Έχουμε βεγαν σουβλάκι στην πίτα (30₪) και επιλογή πίτας χωρίς γλουτένη (40₪) με όλους τους τύπους των σουβλακιών.',
    },
  },
  {
    id: '5',
    question: {
      he: 'איך אפשר להזמין מקום?',
      en: 'How can I reserve a table?',
      ar: 'كيف يمكنني حجز طاولة؟',
      ru: 'Как забронировать столик?',
      el: 'Πώς μπορώ να κάνω κράτηση;',
    },
    answer: {
      he: 'ניתן להתקשר למספר 04-812-2980 או לשלוח הודעת WhatsApp. מומלץ להזמין מקום מראש בסופי שבוע.',
      en: 'You can call 04-812-2980 or send a WhatsApp message. Recommended to reserve in advance on weekends.',
      ar: 'يمكنك الاتصال بالرقم 04-812-2980 أو إرسال رسالة عبر WhatsApp. يُنصح بحجز مكان مسبقًا في عطلة نهاية الأسبوع.',
      ru: 'Можно позвонить по номеру 04-812-2980 или отправить сообщение в WhatsApp. Рекомендуется бронировать столик заранее на выходные.',
      el: 'Μπορείτε να καλέσετε στο 04-812-2980 ή να στείλετε μήνυμα WhatsApp. Προτείνεται να κάνετε κράτηση εκ των προτέρων τα Σαββατοκύριακα.',
    },
  },
  {
    id: '6',
    question: {
      he: 'מה ההבדל בין סובלאקי לגירוס?',
      en: "What's the difference between souvlaki and gyros?",
      ar: 'ما الفرق بين السوفلاكي والجيروس؟',
      ru: 'В чем разница между сувлаки и гирос?',
      el: 'Ποια είναι η διαφορά μεταξύ σουβλάκι και γύρο;',
    },
    answer: {
      he: 'סובלאקי הוא שיפוד בשר צלוי על האש, בעוד גירוס (שווארמה יוונית) הוא בשר שנחתך משיפוד מסתובב. שניהם מוגשים בפיתה יוונית עם ירקות ורטבים.',
      en: 'Souvlaki is meat grilled on a skewer over fire, while gyros (Greek shawarma) is meat sliced from a rotating spit. Both are served in Greek pita with vegetables and sauces.',
      ar: 'السوفلاكي هو لحم مشوي على سيخ فوق النار، بينما الجيروس (شاورما يونانية) هو لحم مقطع من سيخ دوار. كلاهما يقدم في خبز بيتا يوناني مع الخضروات والصلصات.',
      ru: 'Сувлаки — это мясо, жаренное на шампуре над огнем, а гирос (греческая шаурма) — это мясо, нарезанное с вращающегося вертела. Оба подаются в греческой пите с овощами и соусами.',
      el: 'Το σουβλάκι είναι κρέας ψημένο σε σουβλάκι στη φωτιά, ενώ ο γύρος (ελληνική shawarma) είναι κρέας κομμένο από περιστρεφόμενο σούβλα. Και τα δύο σερβίρονται στην πίτα με λαχανικά και σάλτσες.',
    },
  },
];
